apiVersion: v1
kind: Service
metadata:
  name: guardian-backend-svc
spec:
  selector:
    app: guardian-backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: guardian-frontend-svc
spec:
  selector:
    app: guardian-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
